package com.example.demo.models;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * SupplyOrder Value Object.
  * This class is value object representing database table SupplyOrder
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class SupplyOrder implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int supplyOrderId;
    private String status;
    private Integer quantity;
    private Integer employeeId;
    private Integer supplierId;
    private Integer rawMaterialId;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public SupplyOrder () {

    }

    public SupplyOrder (int supplyOrderIdIn) {

          this.supplyOrderId = supplyOrderIdIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getSupplyOrderId() {
          return this.supplyOrderId;
    }
    public void setSupplyOrderId(int supplyOrderIdIn) {
          this.supplyOrderId = supplyOrderIdIn;
    }

    public String getStatus() {
          return this.status;
    }
    public void setStatus(String statusIn) {
          this.status = statusIn;
    }

    public Integer getQuantity() {
          return this.quantity;
    }
    public void setQuantity(Integer quantityIn) {
          this.quantity = quantityIn;
    }

    public Integer getEmployeeId() {
          return this.employeeId;
    }
    public void setEmployeeId(Integer employeeIdIn) {
          this.employeeId = employeeIdIn;
    }

    public Integer getSupplierId() {
          return this.supplierId;
    }
    public void setSupplierId(Integer supplierIdIn) {
          this.supplierId = supplierIdIn;
    }

    public Integer getRawMaterialId() {
          return this.rawMaterialId;
    }
    public void setRawMaterialId(Integer rawMaterialIdIn) {
          this.rawMaterialId = rawMaterialIdIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int supplyOrderIdIn,
          String statusIn,
          Integer quantityIn,
          Integer employeeIdIn,
          Integer supplierIdIn,
          Integer rawMaterialIdIn) {
          this.supplyOrderId = supplyOrderIdIn;
          this.status = statusIn;
          this.quantity = quantityIn;
          this.employeeId = employeeIdIn;
          this.supplierId = supplierIdIn;
          this.rawMaterialId = rawMaterialIdIn;
    }


    /** 
     * hasEqualMapping-method will compare two SupplyOrder instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(SupplyOrder valueObject) {

          if (valueObject.getSupplyOrderId() != this.supplyOrderId) {
                    return(false);
          }
          if (this.status == null) {
                    if (valueObject.getStatus() != null)
                           return(false);
          } else if (!this.status.equals(valueObject.getStatus())) {
                    return(false);
          }
          if (this.quantity == null) {
                    if (valueObject.getQuantity() != null)
                           return(false);
          } else if (!this.quantity.equals(valueObject.getQuantity())) {
                    return(false);
          }
          if (this.employeeId == null) {
                    if (valueObject.getEmployeeId() != null)
                           return(false);
          } else if (!this.employeeId.equals(valueObject.getEmployeeId())) {
                    return(false);
          }
          if (this.supplierId == null) {
                    if (valueObject.getSupplierId() != null)
                           return(false);
          } else if (!this.supplierId.equals(valueObject.getSupplierId())) {
                    return(false);
          }
          if (this.rawMaterialId == null) {
                    if (valueObject.getRawMaterialId() != null)
                           return(false);
          } else if (!this.rawMaterialId.equals(valueObject.getRawMaterialId())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass SupplyOrder, mapping to table SupplyOrder\n");
        out.append("Persistent attributes: \n"); 
        out.append("supplyOrderId = " + this.supplyOrderId + "\n"); 
        out.append("status = " + this.status + "\n"); 
        out.append("quantity = " + this.quantity + "\n"); 
        out.append("employeeId = " + this.employeeId + "\n"); 
        out.append("supplierId = " + this.supplierId + "\n"); 
        out.append("rawMaterialId = " + this.rawMaterialId + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        SupplyOrder cloned = new SupplyOrder();

        cloned.setSupplyOrderId(this.supplyOrderId); 
        if (this.status != null)
             cloned.setStatus(new String(this.status)); 
        if (this.quantity != null)
             cloned.setQuantity(new Integer(this.quantity.intValue())); 
        if (this.employeeId != null)
             cloned.setEmployeeId(new Integer(this.employeeId.intValue())); 
        if (this.supplierId != null)
             cloned.setSupplierId(new Integer(this.supplierId.intValue())); 
        if (this.rawMaterialId != null)
             cloned.setRawMaterialId(new Integer(this.rawMaterialId.intValue())); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
